name: ci
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install test requirements
        run: pip3 install -r requirements.txt

      - name: Configure CMake
        run: cmake -B build

      - name: Build
        run: cmake --build build

      - name: Test
        run: time ./test.sh